name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Install Android SDK and accept licenses
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install openjdk-8-jdk-headless
          wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk.zip
          unzip -q android-sdk.zip -d android-sdk
          export ANDROID_SDK_ROOT=$PWD/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

      - name: Download and unzip Gradle
        run: |
          wget -q https://services.gradle.org/distributions/gradle-7.2-bin.zip
          unzip -q gradle-7.2-bin.zip
          export GRADLE_HOME=$PWD/gradle-7.2
          export PATH=$GRADLE_HOME/bin:$PATH

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0'  # Specify the Flutter version you want

      - name: Build APK
        working-directory: ./android
        run: |
          flutter build apk

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: ./android/app/build/outputs/flutter-apk/app-release.apk
