name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Set up Gradle
        uses: gradle/wrapper-action@v1 # Use v1 here
        with:
          gradle-version: 7.2 # Specify the Gradle version you want

      - name: Set up Android SDK
        uses: react-native-community/setup-android@v2
        with:
          sdk-version: '30
