name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Install Android SDK command-line tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O tools.zip
          unzip tools.zip -d android-sdk
          yes | android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-33"
          echo "export ANDROID_HOME=${RUNNER_WORKSPACE}/android-sdk" >> $GITHUB_ENV
          echo "export PATH=${RUNNER_WORKSPACE}/android-sdk/cmdline-tools/latest/bin:${PATH}" >> $GITHUB_ENV

      - name: Set up Gradle
        uses: gradle/wrapper-action@v2
        with:
          gradle-version: '7.5'
        env:
          GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0'
        env:
          FLUTTER_HOME: ${{ steps.flutter.outputs.flutter-dir }}
          PATH: ${{ steps.flutter.outputs.flutter-dir }}/bin:$PATH

      - name: Build APK
        working-directory: ./And.dev_gitworkflowandroid
        run: |
          flutter build apk

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: ./And.dev_gitworkflow/build/app/outputs/flutter-apk/app-release.apk
