name: Build and Archive APK/AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: redhat/ubi8

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Set Environment Variables
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/adoptopenjdk-17-hotspot" >> $GITHUB_ENV
        echo "PATH=\$JAVA_HOME/bin:\$PATH" >> $GITHUB_ENV

    - name: Display Java Version
      run: java -version

    - name: Install required packages
      run: sudo yum install -y wget unzip curl

    - name: Download Android SDK Command Line Tools
      run: |
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools.zip -d $HOME/android-sdk

    - name: Set up Android SDK
      run: export ANDROID_SDK_ROOT=$HOME/android-sdk

