name: Build and Archive APK/AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest
      options: --user root

    steps:
    - name: Update and Install Packages
      run: |
        apt-get update
        apt-get install -y wget unzip curl git xz-utils

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Set up Java environment
      run: |
        echo "export JAVA_HOME=/opt/jdk-17" >> $GITHUB_ENV
        echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> $GITHUB_ENV

    - name: Display Java Version
      run: java -version

    - name: Download Android SDK Command Line Tools
      run: |
        mkdir /opt/android-sdk
        cd /opt/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip commandlinetools-linux-10406996_latest.zip 
        cd cmdline-tools/
        mkdir latest
        mv bin/ lib/ NOTICE.txt source.properties latest/
        cd latest/bin/
        export PATH=$PATH:/opt/android-sdk/cmdline-tools/latest/bin
        android_home_path="/opt/android-sdk"
        android_sdk_root_path="/opt/android-sdk"
        yes | ./sdkmanager --licenses
        yes | sdkmanager "platform-tools" "build-tools;30.0.3"
        echo "export ANDROID_HOME=${android_home_path}" >> $GITHUB_ENV
        echo "export ANDROID_SDK_ROOT=${android_sdk_root_path}" >> $GITHUB_ENV
        echo "export PATH=\$PATH:${android_home_path}/tools/bin:${android_home_path}/platform-tools" >> $GITHUB_ENV

   
    - name: Install Flutter
      run: |
        cd 
        mkdir /development
        cd /development
        wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.0-stable.tar.xz
        tar xf flutter_linux_3.13.0-stable.tar.xz
        export PATH="$PATH:`pwd`/flutter/bin"
        git config --global --add safe.directory /development/flutter
        flutter config --android-sdk /opt/android-sdk/cmdline-tools/latest/bin
        flutter doctor
        
    - name: Install Gradle
      run: |
         cd 
         mkdir /opt/gradle
         cd /opt/gradle
         wget https://services.gradle.org/distributions/gradle-8.3-bin.zip
         unzip gradle-8.3-bin.zip
         export PATH=$PATH:/opt/gradle/gradle-8.3/bin
         gradle -v

    - name: Navigate to Project Directory
      run: cd android/

    - name: Build APK
      run: |
        flutter create .
        flutter build apk
      

  
   

