name: Build and Archive APK/AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest
      options: --user root

    steps:
    - name: Update and Install Packages
      run: |
        apt-get update
        apt-get install -y wget unzip curl git

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Set up Java environment
      run: |
        echo "export JAVA_HOME=/opt/jdk-17" >> $GITHUB_ENV
        echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> $GITHUB_ENV

    - name: Display Java Version
      run: java -version

    - name: Download Android SDK Command Line Tools
      run: |
        mkdir /opt/android-sdk
        cd /opt/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip commandlinetools-linux-10406996_latest.zip 
        cd cmdline-tools/
        mkdir latest
        mv bin/ lib/ NOTICE.txt source.properties latest/
        cd latest/bin/
        echo "export ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
        echo "export ANDROID_SDK_ROOT=/opt/android-sdk" >> $GITHUB_ENV
        #echo "export PATH=\$PATH:\$ANDROID_HOME/tools/bin:\$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
        yes | /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3"
   
    - name: Download and install Flutter SDK
      run: |
        cd $HOME
        git clone https://github.com/flutter/flutter.git
        export PATH=$PATH:$HOME/flutter/bin
    
    - name: Display Flutter version
      run: flutter --version

    - name: Download and install Gradle
      run: |
        cd $HOME
        sdk install gradle 8.3
    - name: Display Gradle version
      run: gradle --version

