name: Java 17, Android SDK, and Environment Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Set Environment Variables for Java
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/adoptopenjdk-17-hotspot" >> $GITHUB_ENV
          echo "PATH=\$JAVA_HOME/bin:\$PATH" >> $GITHUB_ENV

      - name: Download and Install Android SDK Command Line Tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-10406996_latest.zip -d android-sdk

      - name: Set Android SDK Environment Variables
        run: |
          echo "ANDROID_HOME=\$PWD/android-sdk" >> $GITHUB_ENV
          echo "PATH=\$ANDROID_HOME/cmdline-tools/latest/bin:\$PATH" >> $GITHUB_ENV

      - name: Display Java and Android SDK Versions
        run: |
          java -version
          sdkmanager --version #version
